version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  foodgram-app:
    image: egorovev00/foodgram-project:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/static
      - mediafiles:/media
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - staticfiles:/static
      - mediafiles:/media
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - foodgram-app