version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  app:
    image: egorovev00/foodgram-project:latest
    restart: always
    depends_on:
      - db
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
    env_file:
      - ./.env
    entrypoint: /code/entrypoint.sh

  nginx:
    image: nginx:1.19
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
    restart: always